export PATH="$PATH:$HOME/bin"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export GRIM_DEFAULT_DIR="$HOME/Media/Pictures/Screenshots"
export JUPYTERLAB_DIR="$HOME/.local/share/jupyter/lab"
