general.import = [
    "~/.config/alacritty/alacritty-theme/themes/after_glow.toml",
    "~/.config/alacritty/keybindings.toml"
]

[window]
decorations = "None"
# Sadly no blur on sway.
#opacity = 0.9
blur = true

[font]
size = 20.0
