target-version = "py312"

[tool.ruff.lint]
# Defaults plus all `pydocstyle` rules plus some Flake8 defaults
select = ["E4", "E7", "E9", "F", "W", "C90", "D"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"
